### ISSUE TITLE
Research localisation options

### ISSUE THREAD

**Issue by taylortom** [taylortom/adapt-authoring#5]
### Requirements
- Ability to set app-wide language
- Ability for individual users to set front-end language (would override default setting)
- Ability to add lang strings in any language in each module
- Ability to override all strings from a single location (i.e. a single file), to open up the possibility of creating 'language pack' modules
- API endpoint for front-end access

### Tasks
- [ ] Investigate localisation
- [ ] Working localisation prototype for one module
- [ ] Write any docs necessary to aid future implementation
- [ ] Investigate how to document lang strings

***
Probably makes sense to base module around [Polyglot.js](http://airbnb.io/polyglot.js/) again
